// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtscLqT4yzyLDgx_JwlwS7tKLcIibJfWc',
    appId: '1:394927007368:web:9a2b896fd9f0c80ff7613d',
    messagingSenderId: '394927007368',
    projectId: 'kostku-86ae6',
    authDomain: 'kostku-86ae6.firebaseapp.com',
    storageBucket: 'kostku-86ae6.appspot.com',
    measurementId: 'G-GTYX95Z1VT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNnWwy_h2Bpiqu41lk4BmZUjjYAyt_xV4',
    appId: '1:394927007368:android:47720f99c5bf73f0f7613d',
    messagingSenderId: '394927007368',
    projectId: 'kostku-86ae6',
    storageBucket: 'kostku-86ae6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9uvGcs2nMKUXLqr8Kc6INiqUO0rVINdc',
    appId: '1:394927007368:ios:769a97a5d93179b9f7613d',
    messagingSenderId: '394927007368',
    projectId: 'kostku-86ae6',
    storageBucket: 'kostku-86ae6.appspot.com',
    iosClientId: '394927007368-t9j711g76muak4s5ss63bfi891eu2ubg.apps.googleusercontent.com',
    iosBundleId: 'com.mppl.projectmppl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9uvGcs2nMKUXLqr8Kc6INiqUO0rVINdc',
    appId: '1:394927007368:ios:769a97a5d93179b9f7613d',
    messagingSenderId: '394927007368',
    projectId: 'kostku-86ae6',
    storageBucket: 'kostku-86ae6.appspot.com',
    iosClientId: '394927007368-t9j711g76muak4s5ss63bfi891eu2ubg.apps.googleusercontent.com',
    iosBundleId: 'com.mppl.projectmppl',
  );
}
